name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Semver tags like v1.2.3
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to deploy (defaults to GitHub ref)'
        required: false
        type: string

# Prevent concurrent deployments due to rate limits
concurrency:
  group: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || 'ci-cd' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run quality checks
      run: npm run qualitycheck

    - name: Deploy with EAS
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      uses: ./.github/actions/eas-update
      with:
        expo-token: ${{ secrets.EXPO_TOKEN }}