name: EAS Update

on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Semver tags like v1.2.3
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to deploy (defaults to GitHub ref)'
        required: false
        type: string

# Prevent concurrent deployments due to rate limits
concurrency:
  group: eas-update
  cancel-in-progress: false

jobs:
  eas-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run quality checks and extract test count
      id: tests
      run: |
        # Run quality checks and capture output
        npm run qualitycheck 2>&1 | tee test_output.log
        
        # Extract test count from Jest output
        TEST_COUNT=$(grep -o "Tests:[[:space:]]*[0-9]*[[:space:]]*passed" test_output.log | grep -o "[0-9]*" | head -1)
        echo "test_count=$TEST_COUNT" >> $GITHUB_OUTPUT
        echo "Extracted test count: $TEST_COUNT"

    - name: Update test count badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ secrets.GIST_ID }}
        filename: tractor-test-count.json
        label: Tests
        message: ${{ steps.tests.outputs.test_count }} Passing
        color: brightgreen
        namedLogo: jest

    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        eas-version: 16.10.1
        packager: npm
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Detect version and inject into app.json
      id: version
      uses: ./.github/actions/git-version

    - name: EAS Update
      run: eas update --branch ${{ steps.version.outputs.eas-branch }} --message "Update ${{ steps.version.outputs.full-version }}"
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}