name: EAS Update

on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Semver tags like v1.2.3
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to deploy (defaults to GitHub ref)'
        required: false
        type: string

# Prevent concurrent deployments due to rate limits
concurrency:
  group: eas-update
  cancel-in-progress: false

jobs:
  eas-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run quality checks
      run: npm run qualitycheck

    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Detect version and inject into app.json
      id: vars
      uses: ./.github/actions/git-version.yml

    - name: EAS Update
      run: eas update --branch ${{ steps.vars.outputs.eas-branch }} --message "${{ steps.vars.outputs.eas-message }}"
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}