name: PR Quality Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run quality checks
      run: npm run qualitycheck

    - name: Install EAS CLI globally
      run: npm install -g eas-cli

    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Set deployment variables
      id: vars
      run: |
        PR_NUMBER="${{ github.event.number }}"
        PR_BRANCH="pr-$PR_NUMBER"
        echo "EAS_BRANCH=$PR_BRANCH" >> $GITHUB_OUTPUT
        echo "EAS_MESSAGE=PR #$PR_NUMBER: ${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
        echo "Deploying to PR branch: $PR_BRANCH for PR #$PR_NUMBER"

    - name: EAS Update
      run: npx eas update --branch ${{ steps.vars.outputs.EAS_BRANCH }} --message "${{ steps.vars.outputs.EAS_MESSAGE }}"
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
